plugins loader with npm install and dynamic import (#2317)
* plugins loader with npm install and dynamic import
- replaced the live-plugin-manager with the plugin-installer class
- the plugin-installer uses npm install
- it does not handle race conditions, like the live-plugin-manager does
  but I think we can just call it in a save way (without force flag from workers)
- supports esm and comonJS modules
- we can't use typescript here, because tsc downgrades dynamic imports() to requires

* downgrade to require in jest
- tests with esm are not possible this way

* missed return and import comes from location

* install from git and refactoring

* moved plugin-installer in its own package

* remove the old plugin directory, before installing again

* tarball error handling, github default branch instead of master

* downgraded jest in server, to get rid of error messages
- with 29.x it throws
  TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

* normalize import path

* schema prefix on windows